
a = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]

for j in a:
	for i in a:
		filename = str('master_part_'+str(j)+str(i)+".json")
		print("mongoimport -d discogs_masters -c all_masters "+filename)


   
mongoimport -d discogs_masters -c all_masters master_part_aa.json
mongoimport -d discogs_masters -c all_masters master_part_ab.json
mongoimport -d discogs_masters -c all_masters master_part_ac.json
mongoimport -d discogs_masters -c all_masters master_part_ad.json
mongoimport -d discogs_masters -c all_masters master_part_ae.json
mongoimport -d discogs_masters -c all_masters master_part_af.json
mongoimport -d discogs_masters -c all_masters master_part_ag.json
mongoimport -d discogs_masters -c all_masters master_part_ah.json
mongoimport -d discogs_masters -c all_masters master_part_ai.json
mongoimport -d discogs_masters -c all_masters master_part_aj.json
mongoimport -d discogs_masters -c all_masters master_part_ak.json
mongoimport -d discogs_masters -c all_masters master_part_al.json
mongoimport -d discogs_masters -c all_masters master_part_am.json
mongoimport -d discogs_masters -c all_masters master_part_an.json
mongoimport -d discogs_masters -c all_masters master_part_ao.json
mongoimport -d discogs_masters -c all_masters master_part_ap.json
mongoimport -d discogs_masters -c all_masters master_part_aq.json
mongoimport -d discogs_masters -c all_masters master_part_ar.json
mongoimport -d discogs_masters -c all_masters master_part_as.json
mongoimport -d discogs_masters -c all_masters master_part_at.json
mongoimport -d discogs_masters -c all_masters master_part_au.json
mongoimport -d discogs_masters -c all_masters master_part_av.json
mongoimport -d discogs_masters -c all_masters master_part_aw.json
mongoimport -d discogs_masters -c all_masters master_part_ax.json
mongoimport -d discogs_masters -c all_masters master_part_ay.json
mongoimport -d discogs_masters -c all_masters master_part_az.json

mongoimport -d discogs_masters -c all_masters master_part_ba.json
mongoimport -d discogs_masters -c all_masters master_part_bb.json
mongoimport -d discogs_masters -c all_masters master_part_bc.json
mongoimport -d discogs_masters -c all_masters master_part_bd.json
mongoimport -d discogs_masters -c all_masters master_part_be.json
mongoimport -d discogs_masters -c all_masters master_part_bf.json
mongoimport -d discogs_masters -c all_masters master_part_bg.json
mongoimport -d discogs_masters -c all_masters master_part_bh.json
mongoimport -d discogs_masters -c all_masters master_part_bi.json
mongoimport -d discogs_masters -c all_masters master_part_bj.json
mongoimport -d discogs_masters -c all_masters master_part_bk.json
mongoimport -d discogs_masters -c all_masters master_part_bl.json
mongoimport -d discogs_masters -c all_masters master_part_bm.json
mongoimport -d discogs_masters -c all_masters master_part_bn.json
mongoimport -d discogs_masters -c all_masters master_part_bo.json
mongoimport -d discogs_masters -c all_masters master_part_bp.json
mongoimport -d discogs_masters -c all_masters master_part_bq.json
mongoimport -d discogs_masters -c all_masters master_part_br.json
mongoimport -d discogs_masters -c all_masters master_part_bs.json
mongoimport -d discogs_masters -c all_masters master_part_bt.json
mongoimport -d discogs_masters -c all_masters master_part_bu.json
mongoimport -d discogs_masters -c all_masters master_part_bv.json
mongoimport -d discogs_masters -c all_masters master_part_bw.json
mongoimport -d discogs_masters -c all_masters master_part_bx.json
mongoimport -d discogs_masters -c all_masters master_part_by.json
mongoimport -d discogs_masters -c all_masters master_part_bz.json

mongoimport -d discogs_masters -c all_masters master_part_ca.json
mongoimport -d discogs_masters -c all_masters master_part_cb.json
mongoimport -d discogs_masters -c all_masters master_part_cc.json
mongoimport -d discogs_masters -c all_masters master_part_cd.json
mongoimport -d discogs_masters -c all_masters master_part_ce.json
mongoimport -d discogs_masters -c all_masters master_part_cf.json
mongoimport -d discogs_masters -c all_masters master_part_cg.json
mongoimport -d discogs_masters -c all_masters master_part_ch.json
mongoimport -d discogs_masters -c all_masters master_part_ci.json
mongoimport -d discogs_masters -c all_masters master_part_cj.json
mongoimport -d discogs_masters -c all_masters master_part_ck.json
mongoimport -d discogs_masters -c all_masters master_part_cl.json
mongoimport -d discogs_masters -c all_masters master_part_cm.json
mongoimport -d discogs_masters -c all_masters master_part_cn.json
mongoimport -d discogs_masters -c all_masters master_part_co.json
mongoimport -d discogs_masters -c all_masters master_part_cp.json
mongoimport -d discogs_masters -c all_masters master_part_cq.json
mongoimport -d discogs_masters -c all_masters master_part_cr.json
mongoimport -d discogs_masters -c all_masters master_part_cs.json
mongoimport -d discogs_masters -c all_masters master_part_ct.json
mongoimport -d discogs_masters -c all_masters master_part_cu.json
mongoimport -d discogs_masters -c all_masters master_part_cv.json
mongoimport -d discogs_masters -c all_masters master_part_cw.json
mongoimport -d discogs_masters -c all_masters master_part_cx.json
mongoimport -d discogs_masters -c all_masters master_part_cy.json
mongoimport -d discogs_masters -c all_masters master_part_cz.json

mongoimport -d discogs_masters -c all_masters master_part_da.json
mongoimport -d discogs_masters -c all_masters master_part_db.json
mongoimport -d discogs_masters -c all_masters master_part_dc.json
mongoimport -d discogs_masters -c all_masters master_part_dd.json
mongoimport -d discogs_masters -c all_masters master_part_de.json
mongoimport -d discogs_masters -c all_masters master_part_df.json
mongoimport -d discogs_masters -c all_masters master_part_dg.json
mongoimport -d discogs_masters -c all_masters master_part_dh.json
mongoimport -d discogs_masters -c all_masters master_part_di.json
mongoimport -d discogs_masters -c all_masters master_part_dj.json
mongoimport -d discogs_masters -c all_masters master_part_dk.json
mongoimport -d discogs_masters -c all_masters master_part_dl.json
mongoimport -d discogs_masters -c all_masters master_part_dm.json
mongoimport -d discogs_masters -c all_masters master_part_dn.json
mongoimport -d discogs_masters -c all_masters master_part_do.json
mongoimport -d discogs_masters -c all_masters master_part_dp.json
mongoimport -d discogs_masters -c all_masters master_part_dq.json
mongoimport -d discogs_masters -c all_masters master_part_dr.json
mongoimport -d discogs_masters -c all_masters master_part_ds.json
mongoimport -d discogs_masters -c all_masters master_part_dt.json
mongoimport -d discogs_masters -c all_masters master_part_du.json
mongoimport -d discogs_masters -c all_masters master_part_dv.json
mongoimport -d discogs_masters -c all_masters master_part_dw.json
mongoimport -d discogs_masters -c all_masters master_part_dx.json
mongoimport -d discogs_masters -c all_masters master_part_dy.json
mongoimport -d discogs_masters -c all_masters master_part_dz.json

mongoimport -d discogs_masters -c all_masters master_part_ea.json
mongoimport -d discogs_masters -c all_masters master_part_eb.json
mongoimport -d discogs_masters -c all_masters master_part_ec.json
mongoimport -d discogs_masters -c all_masters master_part_ed.json
mongoimport -d discogs_masters -c all_masters master_part_ee.json
mongoimport -d discogs_masters -c all_masters master_part_ef.json
mongoimport -d discogs_masters -c all_masters master_part_eg.json
mongoimport -d discogs_masters -c all_masters master_part_eh.json
mongoimport -d discogs_masters -c all_masters master_part_ei.json
mongoimport -d discogs_masters -c all_masters master_part_ej.json
mongoimport -d discogs_masters -c all_masters master_part_ek.json
mongoimport -d discogs_masters -c all_masters master_part_el.json
mongoimport -d discogs_masters -c all_masters master_part_em.json
mongoimport -d discogs_masters -c all_masters master_part_en.json
mongoimport -d discogs_masters -c all_masters master_part_eo.json
mongoimport -d discogs_masters -c all_masters master_part_ep.json
mongoimport -d discogs_masters -c all_masters master_part_eq.json
mongoimport -d discogs_masters -c all_masters master_part_er.json
mongoimport -d discogs_masters -c all_masters master_part_es.json
mongoimport -d discogs_masters -c all_masters master_part_et.json
mongoimport -d discogs_masters -c all_masters master_part_eu.json
mongoimport -d discogs_masters -c all_masters master_part_ev.json
mongoimport -d discogs_masters -c all_masters master_part_ew.json
mongoimport -d discogs_masters -c all_masters master_part_ex.json
mongoimport -d discogs_masters -c all_masters master_part_ey.json
mongoimport -d discogs_masters -c all_masters master_part_ez.json

mongoimport -d discogs_masters -c all_masters master_part_fa.json
mongoimport -d discogs_masters -c all_masters master_part_fb.json
mongoimport -d discogs_masters -c all_masters master_part_fc.json
mongoimport -d discogs_masters -c all_masters master_part_fd.json
mongoimport -d discogs_masters -c all_masters master_part_fe.json
mongoimport -d discogs_masters -c all_masters master_part_ff.json
mongoimport -d discogs_masters -c all_masters master_part_fg.json
mongoimport -d discogs_masters -c all_masters master_part_fh.json
mongoimport -d discogs_masters -c all_masters master_part_fi.json
mongoimport -d discogs_masters -c all_masters master_part_fj.json
mongoimport -d discogs_masters -c all_masters master_part_fk.json
mongoimport -d discogs_masters -c all_masters master_part_fl.json
mongoimport -d discogs_masters -c all_masters master_part_fm.json
mongoimport -d discogs_masters -c all_masters master_part_fn.json
mongoimport -d discogs_masters -c all_masters master_part_fo.json
mongoimport -d discogs_masters -c all_masters master_part_fp.json
mongoimport -d discogs_masters -c all_masters master_part_fq.json
mongoimport -d discogs_masters -c all_masters master_part_fr.json
mongoimport -d discogs_masters -c all_masters master_part_fs.json
mongoimport -d discogs_masters -c all_masters master_part_ft.json
mongoimport -d discogs_masters -c all_masters master_part_fu.json
mongoimport -d discogs_masters -c all_masters master_part_fv.json
mongoimport -d discogs_masters -c all_masters master_part_fw.json
mongoimport -d discogs_masters -c all_masters master_part_fx.json
mongoimport -d discogs_masters -c all_masters master_part_fy.json
mongoimport -d discogs_masters -c all_masters master_part_fz.json

mongoimport -d discogs_masters -c all_masters master_part_ga.json
mongoimport -d discogs_masters -c all_masters master_part_gb.json
mongoimport -d discogs_masters -c all_masters master_part_gc.json
mongoimport -d discogs_masters -c all_masters master_part_gd.json
mongoimport -d discogs_masters -c all_masters master_part_ge.json
mongoimport -d discogs_masters -c all_masters master_part_gf.json
mongoimport -d discogs_masters -c all_masters master_part_gg.json
mongoimport -d discogs_masters -c all_masters master_part_gh.json
mongoimport -d discogs_masters -c all_masters master_part_gi.json
mongoimport -d discogs_masters -c all_masters master_part_gj.json
mongoimport -d discogs_masters -c all_masters master_part_gk.json
mongoimport -d discogs_masters -c all_masters master_part_gl.json
mongoimport -d discogs_masters -c all_masters master_part_gm.json
mongoimport -d discogs_masters -c all_masters master_part_gn.json
mongoimport -d discogs_masters -c all_masters master_part_go.json
mongoimport -d discogs_masters -c all_masters master_part_gp.json
mongoimport -d discogs_masters -c all_masters master_part_gq.json
mongoimport -d discogs_masters -c all_masters master_part_gr.json
mongoimport -d discogs_masters -c all_masters master_part_gs.json
mongoimport -d discogs_masters -c all_masters master_part_gt.json
mongoimport -d discogs_masters -c all_masters master_part_gu.json
mongoimport -d discogs_masters -c all_masters master_part_gv.json
mongoimport -d discogs_masters -c all_masters master_part_gw.json
mongoimport -d discogs_masters -c all_masters master_part_gx.json
mongoimport -d discogs_masters -c all_masters master_part_gy.json
mongoimport -d discogs_masters -c all_masters master_part_gz.json

mongoimport -d discogs_masters -c all_masters master_part_ha.json
mongoimport -d discogs_masters -c all_masters master_part_hb.json
mongoimport -d discogs_masters -c all_masters master_part_hc.json
mongoimport -d discogs_masters -c all_masters master_part_hd.json
mongoimport -d discogs_masters -c all_masters master_part_he.json
mongoimport -d discogs_masters -c all_masters master_part_hf.json
mongoimport -d discogs_masters -c all_masters master_part_hg.json
mongoimport -d discogs_masters -c all_masters master_part_hh.json
mongoimport -d discogs_masters -c all_masters master_part_hi.json
mongoimport -d discogs_masters -c all_masters master_part_hj.json
mongoimport -d discogs_masters -c all_masters master_part_hk.json
mongoimport -d discogs_masters -c all_masters master_part_hl.json
mongoimport -d discogs_masters -c all_masters master_part_hm.json
mongoimport -d discogs_masters -c all_masters master_part_hn.json
mongoimport -d discogs_masters -c all_masters master_part_ho.json
mongoimport -d discogs_masters -c all_masters master_part_hp.json
mongoimport -d discogs_masters -c all_masters master_part_hq.json
mongoimport -d discogs_masters -c all_masters master_part_hr.json
mongoimport -d discogs_masters -c all_masters master_part_hs.json
mongoimport -d discogs_masters -c all_masters master_part_ht.json
mongoimport -d discogs_masters -c all_masters master_part_hu.json
mongoimport -d discogs_masters -c all_masters master_part_hv.json
mongoimport -d discogs_masters -c all_masters master_part_hw.json
mongoimport -d discogs_masters -c all_masters master_part_hx.json
mongoimport -d discogs_masters -c all_masters master_part_hy.json
mongoimport -d discogs_masters -c all_masters master_part_hz.json

mongoimport -d discogs_masters -c all_masters master_part_ia.json
mongoimport -d discogs_masters -c all_masters master_part_ib.json
mongoimport -d discogs_masters -c all_masters master_part_ic.json
mongoimport -d discogs_masters -c all_masters master_part_id.json
mongoimport -d discogs_masters -c all_masters master_part_ie.json
mongoimport -d discogs_masters -c all_masters master_part_if.json
mongoimport -d discogs_masters -c all_masters master_part_ig.json
mongoimport -d discogs_masters -c all_masters master_part_ih.json
mongoimport -d discogs_masters -c all_masters master_part_ii.json
mongoimport -d discogs_masters -c all_masters master_part_ij.json
mongoimport -d discogs_masters -c all_masters master_part_ik.json
mongoimport -d discogs_masters -c all_masters master_part_il.json
mongoimport -d discogs_masters -c all_masters master_part_im.json
mongoimport -d discogs_masters -c all_masters master_part_in.json
mongoimport -d discogs_masters -c all_masters master_part_io.json
mongoimport -d discogs_masters -c all_masters master_part_ip.json
mongoimport -d discogs_masters -c all_masters master_part_iq.json
mongoimport -d discogs_masters -c all_masters master_part_ir.json
mongoimport -d discogs_masters -c all_masters master_part_is.json
mongoimport -d discogs_masters -c all_masters master_part_it.json
mongoimport -d discogs_masters -c all_masters master_part_iu.json
mongoimport -d discogs_masters -c all_masters master_part_iv.json
mongoimport -d discogs_masters -c all_masters master_part_iw.json
mongoimport -d discogs_masters -c all_masters master_part_ix.json
mongoimport -d discogs_masters -c all_masters master_part_iy.json
mongoimport -d discogs_masters -c all_masters master_part_iz.json

mongoimport -d discogs_masters -c all_masters master_part_ja.json
mongoimport -d discogs_masters -c all_masters master_part_jb.json
mongoimport -d discogs_masters -c all_masters master_part_jc.json
mongoimport -d discogs_masters -c all_masters master_part_jd.json
mongoimport -d discogs_masters -c all_masters master_part_je.json
mongoimport -d discogs_masters -c all_masters master_part_jf.json
mongoimport -d discogs_masters -c all_masters master_part_jg.json
mongoimport -d discogs_masters -c all_masters master_part_jh.json
mongoimport -d discogs_masters -c all_masters master_part_ji.json
mongoimport -d discogs_masters -c all_masters master_part_jj.json
mongoimport -d discogs_masters -c all_masters master_part_jk.json
mongoimport -d discogs_masters -c all_masters master_part_jl.json
mongoimport -d discogs_masters -c all_masters master_part_jm.json
mongoimport -d discogs_masters -c all_masters master_part_jn.json
mongoimport -d discogs_masters -c all_masters master_part_jo.json
mongoimport -d discogs_masters -c all_masters master_part_jp.json
mongoimport -d discogs_masters -c all_masters master_part_jq.json
mongoimport -d discogs_masters -c all_masters master_part_jr.json
mongoimport -d discogs_masters -c all_masters master_part_js.json
mongoimport -d discogs_masters -c all_masters master_part_jt.json
mongoimport -d discogs_masters -c all_masters master_part_ju.json
mongoimport -d discogs_masters -c all_masters master_part_jv.json
mongoimport -d discogs_masters -c all_masters master_part_jw.json
mongoimport -d discogs_masters -c all_masters master_part_jx.json
mongoimport -d discogs_masters -c all_masters master_part_jy.json
mongoimport -d discogs_masters -c all_masters master_part_jz.json

mongoimport -d discogs_masters -c all_masters master_part_ka.json
mongoimport -d discogs_masters -c all_masters master_part_kb.json
mongoimport -d discogs_masters -c all_masters master_part_kc.json
mongoimport -d discogs_masters -c all_masters master_part_kd.json
mongoimport -d discogs_masters -c all_masters master_part_ke.json
mongoimport -d discogs_masters -c all_masters master_part_kf.json
mongoimport -d discogs_masters -c all_masters master_part_kg.json
mongoimport -d discogs_masters -c all_masters master_part_kh.json
mongoimport -d discogs_masters -c all_masters master_part_ki.json
mongoimport -d discogs_masters -c all_masters master_part_kj.json
mongoimport -d discogs_masters -c all_masters master_part_kk.json
mongoimport -d discogs_masters -c all_masters master_part_kl.json
mongoimport -d discogs_masters -c all_masters master_part_km.json
mongoimport -d discogs_masters -c all_masters master_part_kn.json
mongoimport -d discogs_masters -c all_masters master_part_ko.json
mongoimport -d discogs_masters -c all_masters master_part_kp.json
mongoimport -d discogs_masters -c all_masters master_part_kq.json
mongoimport -d discogs_masters -c all_masters master_part_kr.json
mongoimport -d discogs_masters -c all_masters master_part_ks.json
mongoimport -d discogs_masters -c all_masters master_part_kt.json
mongoimport -d discogs_masters -c all_masters master_part_ku.json
mongoimport -d discogs_masters -c all_masters master_part_kv.json
mongoimport -d discogs_masters -c all_masters master_part_kw.json
mongoimport -d discogs_masters -c all_masters master_part_kx.json
mongoimport -d discogs_masters -c all_masters master_part_ky.json
mongoimport -d discogs_masters -c all_masters master_part_kz.json

mongoimport -d discogs_masters -c all_masters master_part_la.json
mongoimport -d discogs_masters -c all_masters master_part_lb.json
mongoimport -d discogs_masters -c all_masters master_part_lc.json
mongoimport -d discogs_masters -c all_masters master_part_ld.json
mongoimport -d discogs_masters -c all_masters master_part_le.json
mongoimport -d discogs_masters -c all_masters master_part_lf.json
mongoimport -d discogs_masters -c all_masters master_part_lg.json
mongoimport -d discogs_masters -c all_masters master_part_lh.json
mongoimport -d discogs_masters -c all_masters master_part_li.json
mongoimport -d discogs_masters -c all_masters master_part_lj.json
mongoimport -d discogs_masters -c all_masters master_part_lk.json
mongoimport -d discogs_masters -c all_masters master_part_ll.json
mongoimport -d discogs_masters -c all_masters master_part_lm.json
mongoimport -d discogs_masters -c all_masters master_part_ln.json
mongoimport -d discogs_masters -c all_masters master_part_lo.json
mongoimport -d discogs_masters -c all_masters master_part_lp.json
mongoimport -d discogs_masters -c all_masters master_part_lq.json
mongoimport -d discogs_masters -c all_masters master_part_lr.json
mongoimport -d discogs_masters -c all_masters master_part_ls.json
mongoimport -d discogs_masters -c all_masters master_part_lt.json
mongoimport -d discogs_masters -c all_masters master_part_lu.json
mongoimport -d discogs_masters -c all_masters master_part_lv.json
mongoimport -d discogs_masters -c all_masters master_part_lw.json
mongoimport -d discogs_masters -c all_masters master_part_lx.json
mongoimport -d discogs_masters -c all_masters master_part_ly.json
mongoimport -d discogs_masters -c all_masters master_part_lz.json

mongoimport -d discogs_masters -c all_masters master_part_ma.json
mongoimport -d discogs_masters -c all_masters master_part_mb.json
mongoimport -d discogs_masters -c all_masters master_part_mc.json
mongoimport -d discogs_masters -c all_masters master_part_md.json
mongoimport -d discogs_masters -c all_masters master_part_me.json
mongoimport -d discogs_masters -c all_masters master_part_mf.json
mongoimport -d discogs_masters -c all_masters master_part_mg.json
mongoimport -d discogs_masters -c all_masters master_part_mh.json
mongoimport -d discogs_masters -c all_masters master_part_mi.json
mongoimport -d discogs_masters -c all_masters master_part_mj.json
mongoimport -d discogs_masters -c all_masters master_part_mk.json
mongoimport -d discogs_masters -c all_masters master_part_ml.json
mongoimport -d discogs_masters -c all_masters master_part_mm.json
mongoimport -d discogs_masters -c all_masters master_part_mn.json
mongoimport -d discogs_masters -c all_masters master_part_mo.json
mongoimport -d discogs_masters -c all_masters master_part_mp.json
mongoimport -d discogs_masters -c all_masters master_part_mq.json
mongoimport -d discogs_masters -c all_masters master_part_mr.json
mongoimport -d discogs_masters -c all_masters master_part_ms.json
mongoimport -d discogs_masters -c all_masters master_part_mt.json
mongoimport -d discogs_masters -c all_masters master_part_mu.json
mongoimport -d discogs_masters -c all_masters master_part_mv.json
mongoimport -d discogs_masters -c all_masters master_part_mw.json
mongoimport -d discogs_masters -c all_masters master_part_mx.json
mongoimport -d discogs_masters -c all_masters master_part_my.json
mongoimport -d discogs_masters -c all_masters master_part_mz.json

mongoimport -d discogs_masters -c all_masters master_part_na.json
mongoimport -d discogs_masters -c all_masters master_part_nb.json
mongoimport -d discogs_masters -c all_masters master_part_nc.json
mongoimport -d discogs_masters -c all_masters master_part_nd.json
mongoimport -d discogs_masters -c all_masters master_part_ne.json
mongoimport -d discogs_masters -c all_masters master_part_nf.json
mongoimport -d discogs_masters -c all_masters master_part_ng.json
mongoimport -d discogs_masters -c all_masters master_part_nh.json
mongoimport -d discogs_masters -c all_masters master_part_ni.json
mongoimport -d discogs_masters -c all_masters master_part_nj.json
mongoimport -d discogs_masters -c all_masters master_part_nk.json
mongoimport -d discogs_masters -c all_masters master_part_nl.json
mongoimport -d discogs_masters -c all_masters master_part_nm.json
mongoimport -d discogs_masters -c all_masters master_part_nn.json
mongoimport -d discogs_masters -c all_masters master_part_no.json
mongoimport -d discogs_masters -c all_masters master_part_np.json
mongoimport -d discogs_masters -c all_masters master_part_nq.json
mongoimport -d discogs_masters -c all_masters master_part_nr.json
mongoimport -d discogs_masters -c all_masters master_part_ns.json
mongoimport -d discogs_masters -c all_masters master_part_nt.json
mongoimport -d discogs_masters -c all_masters master_part_nu.json
mongoimport -d discogs_masters -c all_masters master_part_nv.json
mongoimport -d discogs_masters -c all_masters master_part_nw.json
mongoimport -d discogs_masters -c all_masters master_part_nx.json
mongoimport -d discogs_masters -c all_masters master_part_ny.json
mongoimport -d discogs_masters -c all_masters master_part_nz.json

mongoimport -d discogs_masters -c all_masters master_part_oa.json
mongoimport -d discogs_masters -c all_masters master_part_ob.json
mongoimport -d discogs_masters -c all_masters master_part_oc.json
mongoimport -d discogs_masters -c all_masters master_part_od.json
mongoimport -d discogs_masters -c all_masters master_part_oe.json
mongoimport -d discogs_masters -c all_masters master_part_of.json
mongoimport -d discogs_masters -c all_masters master_part_og.json
mongoimport -d discogs_masters -c all_masters master_part_oh.json
mongoimport -d discogs_masters -c all_masters master_part_oi.json
mongoimport -d discogs_masters -c all_masters master_part_oj.json
mongoimport -d discogs_masters -c all_masters master_part_ok.json
mongoimport -d discogs_masters -c all_masters master_part_ol.json
mongoimport -d discogs_masters -c all_masters master_part_om.json
mongoimport -d discogs_masters -c all_masters master_part_on.json
mongoimport -d discogs_masters -c all_masters master_part_oo.json
mongoimport -d discogs_masters -c all_masters master_part_op.json
mongoimport -d discogs_masters -c all_masters master_part_oq.json
mongoimport -d discogs_masters -c all_masters master_part_or.json
mongoimport -d discogs_masters -c all_masters master_part_os.json
mongoimport -d discogs_masters -c all_masters master_part_ot.json
mongoimport -d discogs_masters -c all_masters master_part_ou.json
mongoimport -d discogs_masters -c all_masters master_part_ov.json
mongoimport -d discogs_masters -c all_masters master_part_ow.json
mongoimport -d discogs_masters -c all_masters master_part_ox.json
mongoimport -d discogs_masters -c all_masters master_part_oy.json
mongoimport -d discogs_masters -c all_masters master_part_oz.json

mongoimport -d discogs_masters -c all_masters master_part_pa.json
mongoimport -d discogs_masters -c all_masters master_part_pb.json
mongoimport -d discogs_masters -c all_masters master_part_pc.json
mongoimport -d discogs_masters -c all_masters master_part_pd.json
mongoimport -d discogs_masters -c all_masters master_part_pe.json
mongoimport -d discogs_masters -c all_masters master_part_pf.json
mongoimport -d discogs_masters -c all_masters master_part_pg.json
mongoimport -d discogs_masters -c all_masters master_part_ph.json
mongoimport -d discogs_masters -c all_masters master_part_pi.json
mongoimport -d discogs_masters -c all_masters master_part_pj.json
mongoimport -d discogs_masters -c all_masters master_part_pk.json
mongoimport -d discogs_masters -c all_masters master_part_pl.json
mongoimport -d discogs_masters -c all_masters master_part_pm.json
mongoimport -d discogs_masters -c all_masters master_part_pn.json
mongoimport -d discogs_masters -c all_masters master_part_po.json
mongoimport -d discogs_masters -c all_masters master_part_pp.json
mongoimport -d discogs_masters -c all_masters master_part_pq.json
mongoimport -d discogs_masters -c all_masters master_part_pr.json
mongoimport -d discogs_masters -c all_masters master_part_ps.json
mongoimport -d discogs_masters -c all_masters master_part_pt.json
mongoimport -d discogs_masters -c all_masters master_part_pu.json
mongoimport -d discogs_masters -c all_masters master_part_pv.json
mongoimport -d discogs_masters -c all_masters master_part_pw.json
mongoimport -d discogs_masters -c all_masters master_part_px.json
mongoimport -d discogs_masters -c all_masters master_part_py.json
mongoimport -d discogs_masters -c all_masters master_part_pz.json

mongoimport -d discogs_masters -c all_masters master_part_qa.json
mongoimport -d discogs_masters -c all_masters master_part_qb.json
mongoimport -d discogs_masters -c all_masters master_part_qc.json
mongoimport -d discogs_masters -c all_masters master_part_qd.json
mongoimport -d discogs_masters -c all_masters master_part_qe.json
mongoimport -d discogs_masters -c all_masters master_part_qf.json
mongoimport -d discogs_masters -c all_masters master_part_qg.json
mongoimport -d discogs_masters -c all_masters master_part_qh.json
mongoimport -d discogs_masters -c all_masters master_part_qi.json
mongoimport -d discogs_masters -c all_masters master_part_qj.json
mongoimport -d discogs_masters -c all_masters master_part_qk.json
mongoimport -d discogs_masters -c all_masters master_part_ql.json
mongoimport -d discogs_masters -c all_masters master_part_qm.json
mongoimport -d discogs_masters -c all_masters master_part_qn.json
mongoimport -d discogs_masters -c all_masters master_part_qo.json
mongoimport -d discogs_masters -c all_masters master_part_qp.json
mongoimport -d discogs_masters -c all_masters master_part_qq.json
mongoimport -d discogs_masters -c all_masters master_part_qr.json
mongoimport -d discogs_masters -c all_masters master_part_qs.json
mongoimport -d discogs_masters -c all_masters master_part_qt.json
mongoimport -d discogs_masters -c all_masters master_part_qu.json
mongoimport -d discogs_masters -c all_masters master_part_qv.json
mongoimport -d discogs_masters -c all_masters master_part_qw.json
mongoimport -d discogs_masters -c all_masters master_part_qx.json
mongoimport -d discogs_masters -c all_masters master_part_qy.json
mongoimport -d discogs_masters -c all_masters master_part_qz.json

mongoimport -d discogs_masters -c all_masters master_part_ra.json
mongoimport -d discogs_masters -c all_masters master_part_rb.json
mongoimport -d discogs_masters -c all_masters master_part_rc.json
mongoimport -d discogs_masters -c all_masters master_part_rd.json
mongoimport -d discogs_masters -c all_masters master_part_re.json
mongoimport -d discogs_masters -c all_masters master_part_rf.json
mongoimport -d discogs_masters -c all_masters master_part_rg.json
mongoimport -d discogs_masters -c all_masters master_part_rh.json
mongoimport -d discogs_masters -c all_masters master_part_ri.json
mongoimport -d discogs_masters -c all_masters master_part_rj.json
mongoimport -d discogs_masters -c all_masters master_part_rk.json
mongoimport -d discogs_masters -c all_masters master_part_rl.json
mongoimport -d discogs_masters -c all_masters master_part_rm.json
mongoimport -d discogs_masters -c all_masters master_part_rn.json
mongoimport -d discogs_masters -c all_masters master_part_ro.json
mongoimport -d discogs_masters -c all_masters master_part_rp.json
mongoimport -d discogs_masters -c all_masters master_part_rq.json
mongoimport -d discogs_masters -c all_masters master_part_rr.json
mongoimport -d discogs_masters -c all_masters master_part_rs.json
mongoimport -d discogs_masters -c all_masters master_part_rt.json
mongoimport -d discogs_masters -c all_masters master_part_ru.json
mongoimport -d discogs_masters -c all_masters master_part_rv.json
mongoimport -d discogs_masters -c all_masters master_part_rw.json
mongoimport -d discogs_masters -c all_masters master_part_rx.json
mongoimport -d discogs_masters -c all_masters master_part_ry.json
mongoimport -d discogs_masters -c all_masters master_part_rz.json

mongoimport -d discogs_masters -c all_masters master_part_sa.json
mongoimport -d discogs_masters -c all_masters master_part_sb.json
mongoimport -d discogs_masters -c all_masters master_part_sc.json
mongoimport -d discogs_masters -c all_masters master_part_sd.json
mongoimport -d discogs_masters -c all_masters master_part_se.json
mongoimport -d discogs_masters -c all_masters master_part_sf.json
mongoimport -d discogs_masters -c all_masters master_part_sg.json
mongoimport -d discogs_masters -c all_masters master_part_sh.json
mongoimport -d discogs_masters -c all_masters master_part_si.json
mongoimport -d discogs_masters -c all_masters master_part_sj.json
mongoimport -d discogs_masters -c all_masters master_part_sk.json
mongoimport -d discogs_masters -c all_masters master_part_sl.json
mongoimport -d discogs_masters -c all_masters master_part_sm.json
mongoimport -d discogs_masters -c all_masters master_part_sn.json
mongoimport -d discogs_masters -c all_masters master_part_so.json
mongoimport -d discogs_masters -c all_masters master_part_sp.json
mongoimport -d discogs_masters -c all_masters master_part_sq.json
mongoimport -d discogs_masters -c all_masters master_part_sr.json
mongoimport -d discogs_masters -c all_masters master_part_ss.json
mongoimport -d discogs_masters -c all_masters master_part_st.json
mongoimport -d discogs_masters -c all_masters master_part_su.json
mongoimport -d discogs_masters -c all_masters master_part_sv.json
mongoimport -d discogs_masters -c all_masters master_part_sw.json
mongoimport -d discogs_masters -c all_masters master_part_sx.json
mongoimport -d discogs_masters -c all_masters master_part_sy.json
mongoimport -d discogs_masters -c all_masters master_part_sz.json

mongoimport -d discogs_masters -c all_masters master_part_ta.json
mongoimport -d discogs_masters -c all_masters master_part_tb.json
mongoimport -d discogs_masters -c all_masters master_part_tc.json
mongoimport -d discogs_masters -c all_masters master_part_td.json
mongoimport -d discogs_masters -c all_masters master_part_te.json
mongoimport -d discogs_masters -c all_masters master_part_tf.json
mongoimport -d discogs_masters -c all_masters master_part_tg.json
mongoimport -d discogs_masters -c all_masters master_part_th.json
mongoimport -d discogs_masters -c all_masters master_part_ti.json
mongoimport -d discogs_masters -c all_masters master_part_tj.json
mongoimport -d discogs_masters -c all_masters master_part_tk.json
mongoimport -d discogs_masters -c all_masters master_part_tl.json
mongoimport -d discogs_masters -c all_masters master_part_tm.json
mongoimport -d discogs_masters -c all_masters master_part_tn.json
mongoimport -d discogs_masters -c all_masters master_part_to.json
mongoimport -d discogs_masters -c all_masters master_part_tp.json
mongoimport -d discogs_masters -c all_masters master_part_tq.json
mongoimport -d discogs_masters -c all_masters master_part_tr.json
mongoimport -d discogs_masters -c all_masters master_part_ts.json
mongoimport -d discogs_masters -c all_masters master_part_tt.json
mongoimport -d discogs_masters -c all_masters master_part_tu.json
mongoimport -d discogs_masters -c all_masters master_part_tv.json
mongoimport -d discogs_masters -c all_masters master_part_tw.json
mongoimport -d discogs_masters -c all_masters master_part_tx.json
mongoimport -d discogs_masters -c all_masters master_part_ty.json
mongoimport -d discogs_masters -c all_masters master_part_tz.json

mongoimport -d discogs_masters -c all_masters master_part_ua.json
mongoimport -d discogs_masters -c all_masters master_part_ub.json
mongoimport -d discogs_masters -c all_masters master_part_uc.json
mongoimport -d discogs_masters -c all_masters master_part_ud.json
mongoimport -d discogs_masters -c all_masters master_part_ue.json
mongoimport -d discogs_masters -c all_masters master_part_uf.json
mongoimport -d discogs_masters -c all_masters master_part_ug.json
mongoimport -d discogs_masters -c all_masters master_part_uh.json
mongoimport -d discogs_masters -c all_masters master_part_ui.json
mongoimport -d discogs_masters -c all_masters master_part_uj.json
mongoimport -d discogs_masters -c all_masters master_part_uk.json
mongoimport -d discogs_masters -c all_masters master_part_ul.json
mongoimport -d discogs_masters -c all_masters master_part_um.json
mongoimport -d discogs_masters -c all_masters master_part_un.json
mongoimport -d discogs_masters -c all_masters master_part_uo.json
mongoimport -d discogs_masters -c all_masters master_part_up.json
mongoimport -d discogs_masters -c all_masters master_part_uq.json
mongoimport -d discogs_masters -c all_masters master_part_ur.json
mongoimport -d discogs_masters -c all_masters master_part_us.json
mongoimport -d discogs_masters -c all_masters master_part_ut.json
mongoimport -d discogs_masters -c all_masters master_part_uu.json
mongoimport -d discogs_masters -c all_masters master_part_uv.json
mongoimport -d discogs_masters -c all_masters master_part_uw.json
mongoimport -d discogs_masters -c all_masters master_part_ux.json
mongoimport -d discogs_masters -c all_masters master_part_uy.json
mongoimport -d discogs_masters -c all_masters master_part_uz.json

mongoimport -d discogs_masters -c all_masters master_part_va.json
mongoimport -d discogs_masters -c all_masters master_part_vb.json
mongoimport -d discogs_masters -c all_masters master_part_vc.json
mongoimport -d discogs_masters -c all_masters master_part_vd.json
mongoimport -d discogs_masters -c all_masters master_part_ve.json
mongoimport -d discogs_masters -c all_masters master_part_vf.json
mongoimport -d discogs_masters -c all_masters master_part_vg.json
mongoimport -d discogs_masters -c all_masters master_part_vh.json
mongoimport -d discogs_masters -c all_masters master_part_vi.json
mongoimport -d discogs_masters -c all_masters master_part_vj.json
mongoimport -d discogs_masters -c all_masters master_part_vk.json
mongoimport -d discogs_masters -c all_masters master_part_vl.json
mongoimport -d discogs_masters -c all_masters master_part_vm.json
mongoimport -d discogs_masters -c all_masters master_part_vn.json
mongoimport -d discogs_masters -c all_masters master_part_vo.json
mongoimport -d discogs_masters -c all_masters master_part_vp.json
mongoimport -d discogs_masters -c all_masters master_part_vq.json
mongoimport -d discogs_masters -c all_masters master_part_vr.json
mongoimport -d discogs_masters -c all_masters master_part_vs.json
mongoimport -d discogs_masters -c all_masters master_part_vt.json
mongoimport -d discogs_masters -c all_masters master_part_vu.json
mongoimport -d discogs_masters -c all_masters master_part_vv.json
mongoimport -d discogs_masters -c all_masters master_part_vw.json
mongoimport -d discogs_masters -c all_masters master_part_vx.json
mongoimport -d discogs_masters -c all_masters master_part_vy.json
mongoimport -d discogs_masters -c all_masters master_part_vz.json

mongoimport -d discogs_masters -c all_masters master_part_wa.json
mongoimport -d discogs_masters -c all_masters master_part_wb.json
mongoimport -d discogs_masters -c all_masters master_part_wc.json
mongoimport -d discogs_masters -c all_masters master_part_wd.json
mongoimport -d discogs_masters -c all_masters master_part_we.json
mongoimport -d discogs_masters -c all_masters master_part_wf.json
mongoimport -d discogs_masters -c all_masters master_part_wg.json
mongoimport -d discogs_masters -c all_masters master_part_wh.json
mongoimport -d discogs_masters -c all_masters master_part_wi.json
mongoimport -d discogs_masters -c all_masters master_part_wj.json
mongoimport -d discogs_masters -c all_masters master_part_wk.json
mongoimport -d discogs_masters -c all_masters master_part_wl.json
mongoimport -d discogs_masters -c all_masters master_part_wm.json
mongoimport -d discogs_masters -c all_masters master_part_wn.json
mongoimport -d discogs_masters -c all_masters master_part_wo.json
mongoimport -d discogs_masters -c all_masters master_part_wp.json
mongoimport -d discogs_masters -c all_masters master_part_wq.json
mongoimport -d discogs_masters -c all_masters master_part_wr.json
mongoimport -d discogs_masters -c all_masters master_part_ws.json
mongoimport -d discogs_masters -c all_masters master_part_wt.json
mongoimport -d discogs_masters -c all_masters master_part_wu.json
mongoimport -d discogs_masters -c all_masters master_part_wv.json
mongoimport -d discogs_masters -c all_masters master_part_ww.json
mongoimport -d discogs_masters -c all_masters master_part_wx.json
mongoimport -d discogs_masters -c all_masters master_part_wy.json
mongoimport -d discogs_masters -c all_masters master_part_wz.json

mongoimport -d discogs_masters -c all_masters master_part_xa.json
mongoimport -d discogs_masters -c all_masters master_part_xb.json
mongoimport -d discogs_masters -c all_masters master_part_xc.json
mongoimport -d discogs_masters -c all_masters master_part_xd.json
mongoimport -d discogs_masters -c all_masters master_part_xe.json
mongoimport -d discogs_masters -c all_masters master_part_xf.json
mongoimport -d discogs_masters -c all_masters master_part_xg.json
mongoimport -d discogs_masters -c all_masters master_part_xh.json
mongoimport -d discogs_masters -c all_masters master_part_xi.json
mongoimport -d discogs_masters -c all_masters master_part_xj.json
mongoimport -d discogs_masters -c all_masters master_part_xk.json
mongoimport -d discogs_masters -c all_masters master_part_xl.json
mongoimport -d discogs_masters -c all_masters master_part_xm.json
mongoimport -d discogs_masters -c all_masters master_part_xn.json
mongoimport -d discogs_masters -c all_masters master_part_xo.json
mongoimport -d discogs_masters -c all_masters master_part_xp.json
mongoimport -d discogs_masters -c all_masters master_part_xq.json
mongoimport -d discogs_masters -c all_masters master_part_xr.json
mongoimport -d discogs_masters -c all_masters master_part_xs.json
mongoimport -d discogs_masters -c all_masters master_part_xt.json
mongoimport -d discogs_masters -c all_masters master_part_xu.json
mongoimport -d discogs_masters -c all_masters master_part_xv.json
mongoimport -d discogs_masters -c all_masters master_part_xw.json
mongoimport -d discogs_masters -c all_masters master_part_xx.json
mongoimport -d discogs_masters -c all_masters master_part_xy.json
mongoimport -d discogs_masters -c all_masters master_part_xz.json

mongoimport -d discogs_masters -c all_masters master_part_ya.json
mongoimport -d discogs_masters -c all_masters master_part_yb.json
mongoimport -d discogs_masters -c all_masters master_part_yc.json
mongoimport -d discogs_masters -c all_masters master_part_yd.json
mongoimport -d discogs_masters -c all_masters master_part_ye.json
mongoimport -d discogs_masters -c all_masters master_part_yf.json
mongoimport -d discogs_masters -c all_masters master_part_yg.json
mongoimport -d discogs_masters -c all_masters master_part_yh.json
mongoimport -d discogs_masters -c all_masters master_part_yi.json
mongoimport -d discogs_masters -c all_masters master_part_yj.json
mongoimport -d discogs_masters -c all_masters master_part_yk.json
mongoimport -d discogs_masters -c all_masters master_part_yl.json
mongoimport -d discogs_masters -c all_masters master_part_ym.json
mongoimport -d discogs_masters -c all_masters master_part_yn.json
mongoimport -d discogs_masters -c all_masters master_part_yo.json
mongoimport -d discogs_masters -c all_masters master_part_yp.json
mongoimport -d discogs_masters -c all_masters master_part_yq.json
mongoimport -d discogs_masters -c all_masters master_part_yr.json
mongoimport -d discogs_masters -c all_masters master_part_ys.json
mongoimport -d discogs_masters -c all_masters master_part_yt.json
mongoimport -d discogs_masters -c all_masters master_part_yu.json
mongoimport -d discogs_masters -c all_masters master_part_yv.json
mongoimport -d discogs_masters -c all_masters master_part_yw.json
mongoimport -d discogs_masters -c all_masters master_part_yx.json
mongoimport -d discogs_masters -c all_masters master_part_yy.json
mongoimport -d discogs_masters -c all_masters master_part_yz.json

mongoimport -d discogs_masters -c all_masters master_part_za.json
mongoimport -d discogs_masters -c all_masters master_part_zb.json
mongoimport -d discogs_masters -c all_masters master_part_zc.json
mongoimport -d discogs_masters -c all_masters master_part_zd.json
mongoimport -d discogs_masters -c all_masters master_part_ze.json
mongoimport -d discogs_masters -c all_masters master_part_zf.json
mongoimport -d discogs_masters -c all_masters master_part_zg.json
mongoimport -d discogs_masters -c all_masters master_part_zh.json
mongoimport -d discogs_masters -c all_masters master_part_zi.json
mongoimport -d discogs_masters -c all_masters master_part_zj.json
mongoimport -d discogs_masters -c all_masters master_part_zk.json
mongoimport -d discogs_masters -c all_masters master_part_zl.json
mongoimport -d discogs_masters -c all_masters master_part_zm.json
mongoimport -d discogs_masters -c all_masters master_part_zn.json
mongoimport -d discogs_masters -c all_masters master_part_zo.json
mongoimport -d discogs_masters -c all_masters master_part_zp.json
mongoimport -d discogs_masters -c all_masters master_part_zq.json
mongoimport -d discogs_masters -c all_masters master_part_zr.json
mongoimport -d discogs_masters -c all_masters master_part_zs.json
mongoimport -d discogs_masters -c all_masters master_part_zt.json
mongoimport -d discogs_masters -c all_masters master_part_zu.json
mongoimport -d discogs_masters -c all_masters master_part_zv.json
mongoimport -d discogs_masters -c all_masters master_part_zw.json
mongoimport -d discogs_masters -c all_masters master_part_zx.json
mongoimport -d discogs_masters -c all_masters master_part_zy.json
mongoimport -d discogs_masters -c all_masters master_part_zz.json
		