
a = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]

for j in a:
	for i in a:
		filename = str('_master_part_'+str(j)+str(i))
		filenameJSON = str('_master_part_'+str(j)+str(i)+'.json')
		print("python xml2json.py -t xml2json -o "+filenameJSON+" "+filename)







# python xml2json.py -t xml2json -o _master_part_aa.json _master_part_aa
# python xml2json.py -t xml2json -o _master_part_ab.json _master_part_ab
# python xml2json.py -t xml2json -o _master_part_ac.json _master_part_ac
# # python xml2json.py -t xml2json -o _master_part_ad.json _master_part_ad
# python xml2json.py -t xml2json -o _master_part_ae.json _master_part_ae
# python xml2json.py -t xml2json -o _master_part_af.json _master_part_af
# python xml2json.py -t xml2json -o _master_part_ag.json _master_part_ag
# python xml2json.py -t xml2json -o master_part_ah.json master_part_ah
# python xml2json.py -t xml2json -o master_part_ai.json master_part_ai
# python xml2json.py -t xml2json -o master_part_aj.json master_part_aj
# python xml2json.py -t xml2json -o master_part_ak.json master_part_ak
# python xml2json.py -t xml2json -o master_part_al.json master_part_al
# python xml2json.py -t xml2json -o master_part_am.json master_part_am
# python xml2json.py -t xml2json -o master_part_an.json master_part_an
# python xml2json.py -t xml2json -o master_part_ao.json master_part_ao
# python xml2json.py -t xml2json -o master_part_ap.json master_part_ap
# python xml2json.py -t xml2json -o master_part_aq.json master_part_aq
# python xml2json.py -t xml2json -o master_part_ar.json master_part_ar
# python xml2json.py -t xml2json -o master_part_as.json master_part_as
# python xml2json.py -t xml2json -o master_part_at.json master_part_at
# python xml2json.py -t xml2json -o master_part_au.json master_part_au
# python xml2json.py -t xml2json -o master_part_av.json master_part_av
# python xml2json.py -t xml2json -o master_part_aw.json master_part_aw
# python xml2json.py -t xml2json -o master_part_ax.json master_part_ax
# python xml2json.py -t xml2json -o master_part_ay.json master_part_ay
# python xml2json.py -t xml2json -o master_part_az.json master_part_az
# python xml2json.py -t xml2json -o master_part_ba.json master_part_ba
# python xml2json.py -t xml2json -o master_part_bb.json master_part_bb
# python xml2json.py -t xml2json -o master_part_bc.json master_part_bc
# python xml2json.py -t xml2json -o master_part_bd.json master_part_bd
# python xml2json.py -t xml2json -o master_part_be.json master_part_be
# python xml2json.py -t xml2json -o master_part_bf.json master_part_bf
# python xml2json.py -t xml2json -o master_part_bg.json master_part_bg
# python xml2json.py -t xml2json -o master_part_bh.json master_part_bh
# python xml2json.py -t xml2json -o master_part_bi.json master_part_bi
# python xml2json.py -t xml2json -o master_part_bj.json master_part_bj
# python xml2json.py -t xml2json -o master_part_bk.json master_part_bk
# python xml2json.py -t xml2json -o master_part_bl.json master_part_bl
# python xml2json.py -t xml2json -o master_part_bm.json master_part_bm
# python xml2json.py -t xml2json -o master_part_bn.json master_part_bn
# python xml2json.py -t xml2json -o master_part_bo.json master_part_bo
# python xml2json.py -t xml2json -o master_part_bp.json master_part_bp
# python xml2json.py -t xml2json -o master_part_bq.json master_part_bq
# python xml2json.py -t xml2json -o master_part_br.json master_part_br
# python xml2json.py -t xml2json -o master_part_bs.json master_part_bs
# python xml2json.py -t xml2json -o master_part_bt.json master_part_bt
# python xml2json.py -t xml2json -o master_part_bu.json master_part_bu
# python xml2json.py -t xml2json -o master_part_bv.json master_part_bv
# python xml2json.py -t xml2json -o master_part_bw.json master_part_bw
# python xml2json.py -t xml2json -o master_part_bx.json master_part_bx
# python xml2json.py -t xml2json -o master_part_by.json master_part_by
# python xml2json.py -t xml2json -o master_part_bz.json master_part_bz
# python xml2json.py -t xml2json -o master_part_ca.json master_part_ca
# python xml2json.py -t xml2json -o master_part_cb.json master_part_cb
# python xml2json.py -t xml2json -o master_part_cc.json master_part_cc
# python xml2json.py -t xml2json -o master_part_cd.json master_part_cd
# python xml2json.py -t xml2json -o master_part_ce.json master_part_ce
# python xml2json.py -t xml2json -o master_part_cf.json master_part_cf
# python xml2json.py -t xml2json -o master_part_cg.json master_part_cg
# python xml2json.py -t xml2json -o master_part_ch.json master_part_ch
# python xml2json.py -t xml2json -o master_part_ci.json master_part_ci
# python xml2json.py -t xml2json -o master_part_cj.json master_part_cj
# python xml2json.py -t xml2json -o master_part_ck.json master_part_ck
# python xml2json.py -t xml2json -o master_part_cl.json master_part_cl
# python xml2json.py -t xml2json -o master_part_cm.json master_part_cm
# python xml2json.py -t xml2json -o master_part_cn.json master_part_cn
# python xml2json.py -t xml2json -o master_part_co.json master_part_co
# python xml2json.py -t xml2json -o master_part_cp.json master_part_cp
# python xml2json.py -t xml2json -o master_part_cq.json master_part_cq
# python xml2json.py -t xml2json -o master_part_cr.json master_part_cr
# python xml2json.py -t xml2json -o master_part_cs.json master_part_cs
# python xml2json.py -t xml2json -o master_part_ct.json master_part_ct
# python xml2json.py -t xml2json -o master_part_cu.json master_part_cu
# python xml2json.py -t xml2json -o master_part_cv.json master_part_cv
# python xml2json.py -t xml2json -o master_part_cw.json master_part_cw
# python xml2json.py -t xml2json -o master_part_cx.json master_part_cx
# python xml2json.py -t xml2json -o master_part_cy.json master_part_cy
# python xml2json.py -t xml2json -o master_part_cz.json master_part_cz
# python xml2json.py -t xml2json -o master_part_da.json master_part_da
# python xml2json.py -t xml2json -o master_part_db.json master_part_db
# python xml2json.py -t xml2json -o master_part_dc.json master_part_dc
# python xml2json.py -t xml2json -o master_part_dd.json master_part_dd
# python xml2json.py -t xml2json -o master_part_de.json master_part_de
# python xml2json.py -t xml2json -o master_part_df.json master_part_df
# python xml2json.py -t xml2json -o master_part_dg.json master_part_dg
# python xml2json.py -t xml2json -o master_part_dh.json master_part_dh
# python xml2json.py -t xml2json -o master_part_di.json master_part_di
# python xml2json.py -t xml2json -o master_part_dj.json master_part_dj
# python xml2json.py -t xml2json -o master_part_dk.json master_part_dk
# python xml2json.py -t xml2json -o master_part_dl.json master_part_dl
# python xml2json.py -t xml2json -o master_part_dm.json master_part_dm
# python xml2json.py -t xml2json -o master_part_dn.json master_part_dn
# python xml2json.py -t xml2json -o master_part_do.json master_part_do
# python xml2json.py -t xml2json -o master_part_dp.json master_part_dp
# python xml2json.py -t xml2json -o master_part_dq.json master_part_dq
# python xml2json.py -t xml2json -o master_part_dr.json master_part_dr
# python xml2json.py -t xml2json -o master_part_ds.json master_part_ds
# python xml2json.py -t xml2json -o master_part_dt.json master_part_dt
# python xml2json.py -t xml2json -o master_part_du.json master_part_du
# python xml2json.py -t xml2json -o master_part_dv.json master_part_dv
# python xml2json.py -t xml2json -o master_part_dw.json master_part_dw
# python xml2json.py -t xml2json -o master_part_dx.json master_part_dx
# python xml2json.py -t xml2json -o master_part_dy.json master_part_dy
# python xml2json.py -t xml2json -o master_part_dz.json master_part_dz
# python xml2json.py -t xml2json -o master_part_ea.json master_part_ea
# python xml2json.py -t xml2json -o master_part_eb.json master_part_eb
# python xml2json.py -t xml2json -o master_part_ec.json master_part_ec
# python xml2json.py -t xml2json -o master_part_ed.json master_part_ed
# python xml2json.py -t xml2json -o master_part_ee.json master_part_ee
# python xml2json.py -t xml2json -o master_part_ef.json master_part_ef
# python xml2json.py -t xml2json -o master_part_eg.json master_part_eg
# python xml2json.py -t xml2json -o master_part_eh.json master_part_eh
# python xml2json.py -t xml2json -o master_part_ei.json master_part_ei
# python xml2json.py -t xml2json -o master_part_ej.json master_part_ej
# python xml2json.py -t xml2json -o master_part_ek.json master_part_ek
# python xml2json.py -t xml2json -o master_part_el.json master_part_el
# python xml2json.py -t xml2json -o master_part_em.json master_part_em
# python xml2json.py -t xml2json -o master_part_en.json master_part_en
# python xml2json.py -t xml2json -o master_part_eo.json master_part_eo
# python xml2json.py -t xml2json -o master_part_ep.json master_part_ep
# python xml2json.py -t xml2json -o master_part_eq.json master_part_eq
# python xml2json.py -t xml2json -o master_part_er.json master_part_er
# python xml2json.py -t xml2json -o master_part_es.json master_part_es
# python xml2json.py -t xml2json -o master_part_et.json master_part_et
# python xml2json.py -t xml2json -o master_part_eu.json master_part_eu
# python xml2json.py -t xml2json -o master_part_ev.json master_part_ev
# python xml2json.py -t xml2json -o master_part_ew.json master_part_ew
# python xml2json.py -t xml2json -o master_part_ex.json master_part_ex
# python xml2json.py -t xml2json -o master_part_ey.json master_part_ey
# python xml2json.py -t xml2json -o master_part_ez.json master_part_ez
# python xml2json.py -t xml2json -o master_part_fa.json master_part_fa
# python xml2json.py -t xml2json -o master_part_fb.json master_part_fb
# python xml2json.py -t xml2json -o master_part_fc.json master_part_fc
# python xml2json.py -t xml2json -o master_part_fd.json master_part_fd
# python xml2json.py -t xml2json -o master_part_fe.json master_part_fe
# python xml2json.py -t xml2json -o master_part_ff.json master_part_ff
# python xml2json.py -t xml2json -o master_part_fg.json master_part_fg
# python xml2json.py -t xml2json -o master_part_fh.json master_part_fh
# python xml2json.py -t xml2json -o master_part_fi.json master_part_fi
# python xml2json.py -t xml2json -o master_part_fj.json master_part_fj
# python xml2json.py -t xml2json -o master_part_fk.json master_part_fk
# python xml2json.py -t xml2json -o master_part_fl.json master_part_fl
# python xml2json.py -t xml2json -o master_part_fm.json master_part_fm
# python xml2json.py -t xml2json -o master_part_fn.json master_part_fn
# python xml2json.py -t xml2json -o master_part_fo.json master_part_fo
# python xml2json.py -t xml2json -o master_part_fp.json master_part_fp
# python xml2json.py -t xml2json -o master_part_fq.json master_part_fq
# python xml2json.py -t xml2json -o master_part_fr.json master_part_fr
# python xml2json.py -t xml2json -o master_part_fs.json master_part_fs
# python xml2json.py -t xml2json -o master_part_ft.json master_part_ft
# python xml2json.py -t xml2json -o master_part_fu.json master_part_fu
# python xml2json.py -t xml2json -o master_part_fv.json master_part_fv
# python xml2json.py -t xml2json -o master_part_fw.json master_part_fw
# python xml2json.py -t xml2json -o master_part_fx.json master_part_fx
# python xml2json.py -t xml2json -o master_part_fy.json master_part_fy
# python xml2json.py -t xml2json -o master_part_fz.json master_part_fz
# python xml2json.py -t xml2json -o master_part_ga.json master_part_ga
# python xml2json.py -t xml2json -o master_part_gb.json master_part_gb
# python xml2json.py -t xml2json -o master_part_gc.json master_part_gc
# python xml2json.py -t xml2json -o master_part_gd.json master_part_gd
# python xml2json.py -t xml2json -o master_part_ge.json master_part_ge
# python xml2json.py -t xml2json -o master_part_gf.json master_part_gf
# python xml2json.py -t xml2json -o master_part_gg.json master_part_gg
# python xml2json.py -t xml2json -o master_part_gh.json master_part_gh
# python xml2json.py -t xml2json -o master_part_gi.json master_part_gi
# python xml2json.py -t xml2json -o master_part_gj.json master_part_gj
# python xml2json.py -t xml2json -o master_part_gk.json master_part_gk
# python xml2json.py -t xml2json -o master_part_gl.json master_part_gl
# python xml2json.py -t xml2json -o master_part_gm.json master_part_gm
# python xml2json.py -t xml2json -o master_part_gn.json master_part_gn
# python xml2json.py -t xml2json -o master_part_go.json master_part_go
# python xml2json.py -t xml2json -o master_part_gp.json master_part_gp
# python xml2json.py -t xml2json -o master_part_gq.json master_part_gq
# python xml2json.py -t xml2json -o master_part_gr.json master_part_gr
# python xml2json.py -t xml2json -o master_part_gs.json master_part_gs
# python xml2json.py -t xml2json -o master_part_gt.json master_part_gt
# python xml2json.py -t xml2json -o master_part_gu.json master_part_gu
# python xml2json.py -t xml2json -o master_part_gv.json master_part_gv
# python xml2json.py -t xml2json -o master_part_gw.json master_part_gw
# python xml2json.py -t xml2json -o master_part_gx.json master_part_gx
# python xml2json.py -t xml2json -o master_part_gy.json master_part_gy
# python xml2json.py -t xml2json -o master_part_gz.json master_part_gz
# python xml2json.py -t xml2json -o master_part_ha.json master_part_ha
# python xml2json.py -t xml2json -o master_part_hb.json master_part_hb
# python xml2json.py -t xml2json -o master_part_hc.json master_part_hc
# python xml2json.py -t xml2json -o master_part_hd.json master_part_hd
# python xml2json.py -t xml2json -o master_part_he.json master_part_he
# python xml2json.py -t xml2json -o master_part_hf.json master_part_hf
# python xml2json.py -t xml2json -o master_part_hg.json master_part_hg
# python xml2json.py -t xml2json -o master_part_hh.json master_part_hh
# python xml2json.py -t xml2json -o master_part_hi.json master_part_hi
# python xml2json.py -t xml2json -o master_part_hj.json master_part_hj
# python xml2json.py -t xml2json -o master_part_hk.json master_part_hk
# python xml2json.py -t xml2json -o master_part_hl.json master_part_hl
# python xml2json.py -t xml2json -o master_part_hm.json master_part_hm
# python xml2json.py -t xml2json -o master_part_hn.json master_part_hn
# python xml2json.py -t xml2json -o master_part_ho.json master_part_ho
# python xml2json.py -t xml2json -o master_part_hp.json master_part_hp
# python xml2json.py -t xml2json -o master_part_hq.json master_part_hq
# python xml2json.py -t xml2json -o master_part_hr.json master_part_hr
# python xml2json.py -t xml2json -o master_part_hs.json master_part_hs
# python xml2json.py -t xml2json -o master_part_ht.json master_part_ht
# python xml2json.py -t xml2json -o master_part_hu.json master_part_hu
# python xml2json.py -t xml2json -o master_part_hv.json master_part_hv
# python xml2json.py -t xml2json -o master_part_hw.json master_part_hw
# python xml2json.py -t xml2json -o master_part_hx.json master_part_hx
# python xml2json.py -t xml2json -o master_part_hy.json master_part_hy
# python xml2json.py -t xml2json -o master_part_hz.json master_part_hz
# python xml2json.py -t xml2json -o master_part_ia.json master_part_ia
# python xml2json.py -t xml2json -o master_part_ib.json master_part_ib
# python xml2json.py -t xml2json -o master_part_ic.json master_part_ic
# python xml2json.py -t xml2json -o master_part_id.json master_part_id
# python xml2json.py -t xml2json -o master_part_ie.json master_part_ie
# python xml2json.py -t xml2json -o master_part_if.json master_part_if
# python xml2json.py -t xml2json -o master_part_ig.json master_part_ig
# python xml2json.py -t xml2json -o master_part_ih.json master_part_ih
# python xml2json.py -t xml2json -o master_part_ii.json master_part_ii
# python xml2json.py -t xml2json -o master_part_ij.json master_part_ij
# python xml2json.py -t xml2json -o master_part_ik.json master_part_ik
# python xml2json.py -t xml2json -o master_part_il.json master_part_il
# python xml2json.py -t xml2json -o master_part_im.json master_part_im
# python xml2json.py -t xml2json -o master_part_in.json master_part_in
# python xml2json.py -t xml2json -o master_part_io.json master_part_io
# python xml2json.py -t xml2json -o master_part_ip.json master_part_ip
# python xml2json.py -t xml2json -o master_part_iq.json master_part_iq
# python xml2json.py -t xml2json -o master_part_ir.json master_part_ir
# python xml2json.py -t xml2json -o master_part_is.json master_part_is
# python xml2json.py -t xml2json -o master_part_it.json master_part_it
# python xml2json.py -t xml2json -o master_part_iu.json master_part_iu
# python xml2json.py -t xml2json -o master_part_iv.json master_part_iv
# python xml2json.py -t xml2json -o master_part_iw.json master_part_iw
# python xml2json.py -t xml2json -o master_part_ix.json master_part_ix
# python xml2json.py -t xml2json -o master_part_iy.json master_part_iy
# python xml2json.py -t xml2json -o master_part_iz.json master_part_iz
# python xml2json.py -t xml2json -o master_part_ja.json master_part_ja
# python xml2json.py -t xml2json -o master_part_jb.json master_part_jb
# python xml2json.py -t xml2json -o master_part_jc.json master_part_jc
# python xml2json.py -t xml2json -o master_part_jd.json master_part_jd
# python xml2json.py -t xml2json -o master_part_je.json master_part_je
# python xml2json.py -t xml2json -o master_part_jf.json master_part_jf
# python xml2json.py -t xml2json -o master_part_jg.json master_part_jg
# python xml2json.py -t xml2json -o master_part_jh.json master_part_jh
# python xml2json.py -t xml2json -o master_part_ji.json master_part_ji
# python xml2json.py -t xml2json -o master_part_jj.json master_part_jj
# python xml2json.py -t xml2json -o master_part_jk.json master_part_jk
# python xml2json.py -t xml2json -o master_part_jl.json master_part_jl
# python xml2json.py -t xml2json -o master_part_jm.json master_part_jm
# python xml2json.py -t xml2json -o master_part_jn.json master_part_jn
# python xml2json.py -t xml2json -o master_part_jo.json master_part_jo
# python xml2json.py -t xml2json -o master_part_jp.json master_part_jp
# python xml2json.py -t xml2json -o master_part_jq.json master_part_jq
# python xml2json.py -t xml2json -o master_part_jr.json master_part_jr
# python xml2json.py -t xml2json -o master_part_js.json master_part_js
# python xml2json.py -t xml2json -o master_part_jt.json master_part_jt
# python xml2json.py -t xml2json -o master_part_ju.json master_part_ju
# python xml2json.py -t xml2json -o master_part_jv.json master_part_jv
# python xml2json.py -t xml2json -o master_part_jw.json master_part_jw
# python xml2json.py -t xml2json -o master_part_jx.json master_part_jx
# python xml2json.py -t xml2json -o master_part_jy.json master_part_jy
# python xml2json.py -t xml2json -o master_part_jz.json master_part_jz
# python xml2json.py -t xml2json -o master_part_ka.json master_part_ka
# python xml2json.py -t xml2json -o master_part_kb.json master_part_kb
# python xml2json.py -t xml2json -o master_part_kc.json master_part_kc
# python xml2json.py -t xml2json -o master_part_kd.json master_part_kd
# python xml2json.py -t xml2json -o master_part_ke.json master_part_ke
# python xml2json.py -t xml2json -o master_part_kf.json master_part_kf
# python xml2json.py -t xml2json -o master_part_kg.json master_part_kg
# python xml2json.py -t xml2json -o master_part_kh.json master_part_kh
# python xml2json.py -t xml2json -o master_part_ki.json master_part_ki
# python xml2json.py -t xml2json -o master_part_kj.json master_part_kj
# python xml2json.py -t xml2json -o master_part_kk.json master_part_kk
# python xml2json.py -t xml2json -o master_part_kl.json master_part_kl
# python xml2json.py -t xml2json -o master_part_km.json master_part_km
# python xml2json.py -t xml2json -o master_part_kn.json master_part_kn
# python xml2json.py -t xml2json -o master_part_ko.json master_part_ko
# python xml2json.py -t xml2json -o master_part_kp.json master_part_kp
# python xml2json.py -t xml2json -o master_part_kq.json master_part_kq
# python xml2json.py -t xml2json -o master_part_kr.json master_part_kr
# python xml2json.py -t xml2json -o master_part_ks.json master_part_ks
# python xml2json.py -t xml2json -o master_part_kt.json master_part_kt
# python xml2json.py -t xml2json -o master_part_ku.json master_part_ku
# python xml2json.py -t xml2json -o master_part_kv.json master_part_kv
# python xml2json.py -t xml2json -o master_part_kw.json master_part_kw
# python xml2json.py -t xml2json -o master_part_kx.json master_part_kx
# python xml2json.py -t xml2json -o master_part_ky.json master_part_ky
# python xml2json.py -t xml2json -o master_part_kz.json master_part_kz
# python xml2json.py -t xml2json -o master_part_la.json master_part_la
# python xml2json.py -t xml2json -o master_part_lb.json master_part_lb
# python xml2json.py -t xml2json -o master_part_lc.json master_part_lc
# python xml2json.py -t xml2json -o master_part_ld.json master_part_ld
# python xml2json.py -t xml2json -o master_part_le.json master_part_le
# python xml2json.py -t xml2json -o master_part_lf.json master_part_lf
# python xml2json.py -t xml2json -o master_part_lg.json master_part_lg
# python xml2json.py -t xml2json -o master_part_lh.json master_part_lh
# python xml2json.py -t xml2json -o master_part_li.json master_part_li
# python xml2json.py -t xml2json -o master_part_lj.json master_part_lj
# python xml2json.py -t xml2json -o master_part_lk.json master_part_lk
# python xml2json.py -t xml2json -o master_part_ll.json master_part_ll
# python xml2json.py -t xml2json -o master_part_lm.json master_part_lm
# python xml2json.py -t xml2json -o master_part_ln.json master_part_ln
# python xml2json.py -t xml2json -o master_part_lo.json master_part_lo
# python xml2json.py -t xml2json -o master_part_lp.json master_part_lp
# python xml2json.py -t xml2json -o master_part_lq.json master_part_lq
# python xml2json.py -t xml2json -o master_part_lr.json master_part_lr
# python xml2json.py -t xml2json -o master_part_ls.json master_part_ls
# python xml2json.py -t xml2json -o master_part_lt.json master_part_lt
# python xml2json.py -t xml2json -o master_part_lu.json master_part_lu
# python xml2json.py -t xml2json -o master_part_lv.json master_part_lv
# python xml2json.py -t xml2json -o master_part_lw.json master_part_lw
# python xml2json.py -t xml2json -o master_part_lx.json master_part_lx
# python xml2json.py -t xml2json -o master_part_ly.json master_part_ly
# python xml2json.py -t xml2json -o master_part_lz.json master_part_lz
# python xml2json.py -t xml2json -o master_part_ma.json master_part_ma
# python xml2json.py -t xml2json -o master_part_mb.json master_part_mb
# python xml2json.py -t xml2json -o master_part_mc.json master_part_mc
# python xml2json.py -t xml2json -o master_part_md.json master_part_md
# python xml2json.py -t xml2json -o master_part_me.json master_part_me
# python xml2json.py -t xml2json -o master_part_mf.json master_part_mf
# python xml2json.py -t xml2json -o master_part_mg.json master_part_mg
# python xml2json.py -t xml2json -o master_part_mh.json master_part_mh
# python xml2json.py -t xml2json -o master_part_mi.json master_part_mi
# python xml2json.py -t xml2json -o master_part_mj.json master_part_mj
# python xml2json.py -t xml2json -o master_part_mk.json master_part_mk
# python xml2json.py -t xml2json -o master_part_ml.json master_part_ml
# python xml2json.py -t xml2json -o master_part_mm.json master_part_mm
# python xml2json.py -t xml2json -o master_part_mn.json master_part_mn
# python xml2json.py -t xml2json -o master_part_mo.json master_part_mo
# python xml2json.py -t xml2json -o master_part_mp.json master_part_mp
# python xml2json.py -t xml2json -o master_part_mq.json master_part_mq
# python xml2json.py -t xml2json -o master_part_mr.json master_part_mr
python xml2json.py -t xml2json -o master_part_ms.json master_part_ms
python xml2json.py -t xml2json -o master_part_mt.json master_part_mt
# python xml2json.py -t xml2json -o master_part_mu.json master_part_mu
# python xml2json.py -t xml2json -o master_part_mv.json master_part_mv
# python xml2json.py -t xml2json -o master_part_mw.json master_part_mw
# python xml2json.py -t xml2json -o master_part_mx.json master_part_mx
# python xml2json.py -t xml2json -o master_part_my.json master_part_my
# python xml2json.py -t xml2json -o master_part_mz.json master_part_mz
# python xml2json.py -t xml2json -o master_part_na.json master_part_na
# python xml2json.py -t xml2json -o master_part_nb.json master_part_nb
# python xml2json.py -t xml2json -o master_part_nc.json master_part_nc
# python xml2json.py -t xml2json -o master_part_nd.json master_part_nd
# python xml2json.py -t xml2json -o master_part_ne.json master_part_ne
# python xml2json.py -t xml2json -o master_part_nf.json master_part_nf
# python xml2json.py -t xml2json -o master_part_ng.json master_part_ng
# python xml2json.py -t xml2json -o master_part_nh.json master_part_nh
# python xml2json.py -t xml2json -o master_part_ni.json master_part_ni
# python xml2json.py -t xml2json -o master_part_nj.json master_part_nj
# python xml2json.py -t xml2json -o master_part_nk.json master_part_nk
# python xml2json.py -t xml2json -o master_part_nl.json master_part_nl
# python xml2json.py -t xml2json -o master_part_nm.json master_part_nm
# python xml2json.py -t xml2json -o master_part_nn.json master_part_nn
# python xml2json.py -t xml2json -o master_part_no.json master_part_no
# python xml2json.py -t xml2json -o master_part_np.json master_part_np
# python xml2json.py -t xml2json -o master_part_nq.json master_part_nq
# python xml2json.py -t xml2json -o master_part_nr.json master_part_nr
# python xml2json.py -t xml2json -o master_part_ns.json master_part_ns
# python xml2json.py -t xml2json -o master_part_nt.json master_part_nt
# python xml2json.py -t xml2json -o master_part_nu.json master_part_nu
# python xml2json.py -t xml2json -o master_part_nv.json master_part_nv
# python xml2json.py -t xml2json -o master_part_nw.json master_part_nw
# python xml2json.py -t xml2json -o master_part_nx.json master_part_nx
# python xml2json.py -t xml2json -o master_part_ny.json master_part_ny
# python xml2json.py -t xml2json -o master_part_nz.json master_part_nz
# python xml2json.py -t xml2json -o master_part_oa.json master_part_oa
# python xml2json.py -t xml2json -o master_part_ob.json master_part_ob
# python xml2json.py -t xml2json -o master_part_oc.json master_part_oc
# python xml2json.py -t xml2json -o master_part_od.json master_part_od
# python xml2json.py -t xml2json -o master_part_oe.json master_part_oe
# python xml2json.py -t xml2json -o master_part_of.json master_part_of
# python xml2json.py -t xml2json -o master_part_og.json master_part_og
# python xml2json.py -t xml2json -o master_part_oh.json master_part_oh
# python xml2json.py -t xml2json -o master_part_oi.json master_part_oi
# python xml2json.py -t xml2json -o master_part_oj.json master_part_oj
# python xml2json.py -t xml2json -o master_part_ok.json master_part_ok
# python xml2json.py -t xml2json -o master_part_ol.json master_part_ol
# python xml2json.py -t xml2json -o master_part_om.json master_part_om
# python xml2json.py -t xml2json -o master_part_on.json master_part_on
# python xml2json.py -t xml2json -o master_part_oo.json master_part_oo
# python xml2json.py -t xml2json -o master_part_op.json master_part_op
# python xml2json.py -t xml2json -o master_part_oq.json master_part_oq
# python xml2json.py -t xml2json -o master_part_or.json master_part_or
# python xml2json.py -t xml2json -o master_part_os.json master_part_os
# python xml2json.py -t xml2json -o master_part_ot.json master_part_ot
# python xml2json.py -t xml2json -o master_part_ou.json master_part_ou
# python xml2json.py -t xml2json -o master_part_ov.json master_part_ov
# python xml2json.py -t xml2json -o master_part_ow.json master_part_ow
# python xml2json.py -t xml2json -o master_part_ox.json master_part_ox
# python xml2json.py -t xml2json -o master_part_oy.json master_part_oy
# python xml2json.py -t xml2json -o master_part_oz.json master_part_oz
# python xml2json.py -t xml2json -o master_part_pa.json master_part_pa
# python xml2json.py -t xml2json -o master_part_pb.json master_part_pb
# python xml2json.py -t xml2json -o master_part_pc.json master_part_pc
# python xml2json.py -t xml2json -o master_part_pd.json master_part_pd
# python xml2json.py -t xml2json -o master_part_pe.json master_part_pe
# python xml2json.py -t xml2json -o master_part_pf.json master_part_pf
# python xml2json.py -t xml2json -o master_part_pg.json master_part_pg
# python xml2json.py -t xml2json -o master_part_ph.json master_part_ph
# python xml2json.py -t xml2json -o master_part_pi.json master_part_pi
# python xml2json.py -t xml2json -o master_part_pj.json master_part_pj
# python xml2json.py -t xml2json -o master_part_pk.json master_part_pk
# python xml2json.py -t xml2json -o master_part_pl.json master_part_pl
# python xml2json.py -t xml2json -o master_part_pm.json master_part_pm
# python xml2json.py -t xml2json -o master_part_pn.json master_part_pn
# python xml2json.py -t xml2json -o master_part_po.json master_part_po
# python xml2json.py -t xml2json -o master_part_pp.json master_part_pp
# python xml2json.py -t xml2json -o master_part_pq.json master_part_pq
# python xml2json.py -t xml2json -o master_part_pr.json master_part_pr
# python xml2json.py -t xml2json -o master_part_ps.json master_part_ps
# python xml2json.py -t xml2json -o master_part_pt.json master_part_pt
# python xml2json.py -t xml2json -o master_part_pu.json master_part_pu
# python xml2json.py -t xml2json -o master_part_pv.json master_part_pv
# python xml2json.py -t xml2json -o master_part_pw.json master_part_pw
# python xml2json.py -t xml2json -o master_part_px.json master_part_px
# python xml2json.py -t xml2json -o master_part_py.json master_part_py
# python xml2json.py -t xml2json -o master_part_pz.json master_part_pz
# python xml2json.py -t xml2json -o master_part_qa.json master_part_qa
# python xml2json.py -t xml2json -o master_part_qb.json master_part_qb
# python xml2json.py -t xml2json -o master_part_qc.json master_part_qc
# python xml2json.py -t xml2json -o master_part_qd.json master_part_qd
# python xml2json.py -t xml2json -o master_part_qe.json master_part_qe
# python xml2json.py -t xml2json -o master_part_qf.json master_part_qf
# python xml2json.py -t xml2json -o master_part_qg.json master_part_qg
# python xml2json.py -t xml2json -o master_part_qh.json master_part_qh
# python xml2json.py -t xml2json -o master_part_qi.json master_part_qi
# python xml2json.py -t xml2json -o master_part_qj.json master_part_qj
# python xml2json.py -t xml2json -o master_part_qk.json master_part_qk
# python xml2json.py -t xml2json -o master_part_ql.json master_part_ql
# python xml2json.py -t xml2json -o master_part_qm.json master_part_qm
# python xml2json.py -t xml2json -o master_part_qn.json master_part_qn
# python xml2json.py -t xml2json -o master_part_qo.json master_part_qo
# python xml2json.py -t xml2json -o master_part_qp.json master_part_qp
# python xml2json.py -t xml2json -o master_part_qq.json master_part_qq
# python xml2json.py -t xml2json -o master_part_qr.json master_part_qr
# python xml2json.py -t xml2json -o master_part_qs.json master_part_qs
# python xml2json.py -t xml2json -o master_part_qt.json master_part_qt
# python xml2json.py -t xml2json -o master_part_qu.json master_part_qu
# python xml2json.py -t xml2json -o master_part_qv.json master_part_qv
# python xml2json.py -t xml2json -o master_part_qw.json master_part_qw
# python xml2json.py -t xml2json -o master_part_qx.json master_part_qx
# python xml2json.py -t xml2json -o master_part_qy.json master_part_qy
# python xml2json.py -t xml2json -o master_part_qz.json master_part_qz
# python xml2json.py -t xml2json -o master_part_ra.json master_part_ra
# python xml2json.py -t xml2json -o master_part_rb.json master_part_rb
# python xml2json.py -t xml2json -o master_part_rc.json master_part_rc
# python xml2json.py -t xml2json -o master_part_rd.json master_part_rd
# python xml2json.py -t xml2json -o master_part_re.json master_part_re
# python xml2json.py -t xml2json -o master_part_rf.json master_part_rf
# python xml2json.py -t xml2json -o master_part_rg.json master_part_rg
# python xml2json.py -t xml2json -o master_part_rh.json master_part_rh
# python xml2json.py -t xml2json -o master_part_ri.json master_part_ri
# python xml2json.py -t xml2json -o master_part_rj.json master_part_rj
# python xml2json.py -t xml2json -o master_part_rk.json master_part_rk
# python xml2json.py -t xml2json -o master_part_rl.json master_part_rl
# python xml2json.py -t xml2json -o master_part_rm.json master_part_rm
# python xml2json.py -t xml2json -o master_part_rn.json master_part_rn
# python xml2json.py -t xml2json -o master_part_ro.json master_part_ro
# python xml2json.py -t xml2json -o master_part_rp.json master_part_rp
# python xml2json.py -t xml2json -o master_part_rq.json master_part_rq
# python xml2json.py -t xml2json -o master_part_rr.json master_part_rr
# python xml2json.py -t xml2json -o master_part_rs.json master_part_rs
# python xml2json.py -t xml2json -o master_part_rt.json master_part_rt
# python xml2json.py -t xml2json -o master_part_ru.json master_part_ru
# python xml2json.py -t xml2json -o master_part_rv.json master_part_rv
# python xml2json.py -t xml2json -o master_part_rw.json master_part_rw
# python xml2json.py -t xml2json -o master_part_rx.json master_part_rx
# python xml2json.py -t xml2json -o master_part_ry.json master_part_ry
# python xml2json.py -t xml2json -o master_part_rz.json master_part_rz
# python xml2json.py -t xml2json -o master_part_sa.json master_part_sa
# python xml2json.py -t xml2json -o master_part_sb.json master_part_sb
# python xml2json.py -t xml2json -o master_part_sc.json master_part_sc
# python xml2json.py -t xml2json -o master_part_sd.json master_part_sd
# python xml2json.py -t xml2json -o master_part_se.json master_part_se
# python xml2json.py -t xml2json -o master_part_sf.json master_part_sf
# python xml2json.py -t xml2json -o master_part_sg.json master_part_sg
# python xml2json.py -t xml2json -o master_part_sh.json master_part_sh
# python xml2json.py -t xml2json -o master_part_si.json master_part_si
# python xml2json.py -t xml2json -o master_part_sj.json master_part_sj
# python xml2json.py -t xml2json -o master_part_sk.json master_part_sk
# python xml2json.py -t xml2json -o master_part_sl.json master_part_sl
# python xml2json.py -t xml2json -o master_part_sm.json master_part_sm
# python xml2json.py -t xml2json -o master_part_sn.json master_part_sn
# python xml2json.py -t xml2json -o master_part_so.json master_part_so
# python xml2json.py -t xml2json -o master_part_sp.json master_part_sp
# python xml2json.py -t xml2json -o master_part_sq.json master_part_sq
# python xml2json.py -t xml2json -o master_part_sr.json master_part_sr
# python xml2json.py -t xml2json -o master_part_ss.json master_part_ss
# python xml2json.py -t xml2json -o master_part_st.json master_part_st
# python xml2json.py -t xml2json -o master_part_su.json master_part_su
# python xml2json.py -t xml2json -o master_part_sv.json master_part_sv
# python xml2json.py -t xml2json -o master_part_sw.json master_part_sw
# python xml2json.py -t xml2json -o master_part_sx.json master_part_sx
# python xml2json.py -t xml2json -o master_part_sy.json master_part_sy
# python xml2json.py -t xml2json -o master_part_sz.json master_part_sz
# python xml2json.py -t xml2json -o master_part_ta.json master_part_ta
# python xml2json.py -t xml2json -o master_part_tb.json master_part_tb
# python xml2json.py -t xml2json -o master_part_tc.json master_part_tc
# python xml2json.py -t xml2json -o master_part_td.json master_part_td
# python xml2json.py -t xml2json -o master_part_te.json master_part_te
# python xml2json.py -t xml2json -o master_part_tf.json master_part_tf
# python xml2json.py -t xml2json -o master_part_tg.json master_part_tg
# python xml2json.py -t xml2json -o master_part_th.json master_part_th
# python xml2json.py -t xml2json -o master_part_ti.json master_part_ti
# python xml2json.py -t xml2json -o master_part_tj.json master_part_tj
# python xml2json.py -t xml2json -o master_part_tk.json master_part_tk
# python xml2json.py -t xml2json -o master_part_tl.json master_part_tl
# python xml2json.py -t xml2json -o master_part_tm.json master_part_tm
# python xml2json.py -t xml2json -o master_part_tn.json master_part_tn
# python xml2json.py -t xml2json -o master_part_to.json master_part_to
# python xml2json.py -t xml2json -o master_part_tp.json master_part_tp
# python xml2json.py -t xml2json -o master_part_tq.json master_part_tq
# python xml2json.py -t xml2json -o master_part_tr.json master_part_tr
# python xml2json.py -t xml2json -o master_part_ts.json master_part_ts
# python xml2json.py -t xml2json -o master_part_tt.json master_part_tt
# python xml2json.py -t xml2json -o master_part_tu.json master_part_tu
# python xml2json.py -t xml2json -o master_part_tv.json master_part_tv
# python xml2json.py -t xml2json -o master_part_tw.json master_part_tw
# python xml2json.py -t xml2json -o master_part_tx.json master_part_tx
# python xml2json.py -t xml2json -o master_part_ty.json master_part_ty
# python xml2json.py -t xml2json -o master_part_tz.json master_part_tz
# python xml2json.py -t xml2json -o master_part_ua.json master_part_ua
# python xml2json.py -t xml2json -o master_part_ub.json master_part_ub
# python xml2json.py -t xml2json -o master_part_uc.json master_part_uc
# python xml2json.py -t xml2json -o master_part_ud.json master_part_ud
# python xml2json.py -t xml2json -o master_part_ue.json master_part_ue
# python xml2json.py -t xml2json -o master_part_uf.json master_part_uf
# python xml2json.py -t xml2json -o master_part_ug.json master_part_ug
# python xml2json.py -t xml2json -o master_part_uh.json master_part_uh
# python xml2json.py -t xml2json -o master_part_ui.json master_part_ui
# python xml2json.py -t xml2json -o master_part_uj.json master_part_uj
# python xml2json.py -t xml2json -o master_part_uk.json master_part_uk
# python xml2json.py -t xml2json -o master_part_ul.json master_part_ul
# python xml2json.py -t xml2json -o master_part_um.json master_part_um
# python xml2json.py -t xml2json -o master_part_un.json master_part_un
# python xml2json.py -t xml2json -o master_part_uo.json master_part_uo
# python xml2json.py -t xml2json -o master_part_up.json master_part_up
# python xml2json.py -t xml2json -o master_part_uq.json master_part_uq
# python xml2json.py -t xml2json -o master_part_ur.json master_part_ur
# python xml2json.py -t xml2json -o master_part_us.json master_part_us
# python xml2json.py -t xml2json -o master_part_ut.json master_part_ut
# python xml2json.py -t xml2json -o master_part_uu.json master_part_uu
# python xml2json.py -t xml2json -o master_part_uv.json master_part_uv
# python xml2json.py -t xml2json -o master_part_uw.json master_part_uw
# python xml2json.py -t xml2json -o master_part_ux.json master_part_ux
# python xml2json.py -t xml2json -o master_part_uy.json master_part_uy
# python xml2json.py -t xml2json -o master_part_uz.json master_part_uz
# python xml2json.py -t xml2json -o master_part_va.json master_part_va
# python xml2json.py -t xml2json -o master_part_vb.json master_part_vb
# python xml2json.py -t xml2json -o master_part_vc.json master_part_vc
# python xml2json.py -t xml2json -o master_part_vd.json master_part_vd
# python xml2json.py -t xml2json -o master_part_ve.json master_part_ve
# python xml2json.py -t xml2json -o master_part_vf.json master_part_vf
# python xml2json.py -t xml2json -o master_part_vg.json master_part_vg
# python xml2json.py -t xml2json -o master_part_vh.json master_part_vh
# python xml2json.py -t xml2json -o master_part_vi.json master_part_vi
# python xml2json.py -t xml2json -o master_part_vj.json master_part_vj
# python xml2json.py -t xml2json -o master_part_vk.json master_part_vk
# python xml2json.py -t xml2json -o master_part_vl.json master_part_vl
# python xml2json.py -t xml2json -o master_part_vm.json master_part_vm
# python xml2json.py -t xml2json -o master_part_vn.json master_part_vn
# python xml2json.py -t xml2json -o master_part_vo.json master_part_vo
# python xml2json.py -t xml2json -o master_part_vp.json master_part_vp
# python xml2json.py -t xml2json -o master_part_vq.json master_part_vq
# python xml2json.py -t xml2json -o master_part_vr.json master_part_vr
# python xml2json.py -t xml2json -o master_part_vs.json master_part_vs
# python xml2json.py -t xml2json -o master_part_vt.json master_part_vt
# python xml2json.py -t xml2json -o master_part_vu.json master_part_vu
# python xml2json.py -t xml2json -o master_part_vv.json master_part_vv
# python xml2json.py -t xml2json -o master_part_vw.json master_part_vw
# python xml2json.py -t xml2json -o master_part_vx.json master_part_vx
# python xml2json.py -t xml2json -o master_part_vy.json master_part_vy
# python xml2json.py -t xml2json -o master_part_vz.json master_part_vz
# python xml2json.py -t xml2json -o master_part_wa.json master_part_wa
# python xml2json.py -t xml2json -o master_part_wb.json master_part_wb
# python xml2json.py -t xml2json -o master_part_wc.json master_part_wc
# python xml2json.py -t xml2json -o master_part_wd.json master_part_wd
# python xml2json.py -t xml2json -o master_part_we.json master_part_we
# python xml2json.py -t xml2json -o master_part_wf.json master_part_wf
# python xml2json.py -t xml2json -o master_part_wg.json master_part_wg
# python xml2json.py -t xml2json -o master_part_wh.json master_part_wh
# python xml2json.py -t xml2json -o master_part_wi.json master_part_wi
# python xml2json.py -t xml2json -o master_part_wj.json master_part_wj
# python xml2json.py -t xml2json -o master_part_wk.json master_part_wk
# python xml2json.py -t xml2json -o master_part_wl.json master_part_wl
# python xml2json.py -t xml2json -o master_part_wm.json master_part_wm
# python xml2json.py -t xml2json -o master_part_wn.json master_part_wn
# python xml2json.py -t xml2json -o master_part_wo.json master_part_wo
# python xml2json.py -t xml2json -o master_part_wp.json master_part_wp
# python xml2json.py -t xml2json -o master_part_wq.json master_part_wq
# python xml2json.py -t xml2json -o master_part_wr.json master_part_wr
# python xml2json.py -t xml2json -o master_part_ws.json master_part_ws
# python xml2json.py -t xml2json -o master_part_wt.json master_part_wt
# python xml2json.py -t xml2json -o master_part_wu.json master_part_wu
# python xml2json.py -t xml2json -o master_part_wv.json master_part_wv
# python xml2json.py -t xml2json -o master_part_ww.json master_part_ww
# python xml2json.py -t xml2json -o master_part_wx.json master_part_wx
# python xml2json.py -t xml2json -o master_part_wy.json master_part_wy
# python xml2json.py -t xml2json -o master_part_wz.json master_part_wz
# python xml2json.py -t xml2json -o master_part_xa.json master_part_xa
# python xml2json.py -t xml2json -o master_part_xb.json master_part_xb
# python xml2json.py -t xml2json -o master_part_xc.json master_part_xc
# python xml2json.py -t xml2json -o master_part_xd.json master_part_xd
# python xml2json.py -t xml2json -o master_part_xe.json master_part_xe
# python xml2json.py -t xml2json -o master_part_xf.json master_part_xf
# python xml2json.py -t xml2json -o master_part_xg.json master_part_xg
# python xml2json.py -t xml2json -o master_part_xh.json master_part_xh
# python xml2json.py -t xml2json -o master_part_xi.json master_part_xi
# python xml2json.py -t xml2json -o master_part_xj.json master_part_xj
# python xml2json.py -t xml2json -o master_part_xk.json master_part_xk
# python xml2json.py -t xml2json -o master_part_xl.json master_part_xl
# python xml2json.py -t xml2json -o master_part_xm.json master_part_xm
# python xml2json.py -t xml2json -o master_part_xn.json master_part_xn
# python xml2json.py -t xml2json -o master_part_xo.json master_part_xo
# python xml2json.py -t xml2json -o master_part_xp.json master_part_xp
# python xml2json.py -t xml2json -o master_part_xq.json master_part_xq
# python xml2json.py -t xml2json -o master_part_xr.json master_part_xr
# python xml2json.py -t xml2json -o master_part_xs.json master_part_xs
# python xml2json.py -t xml2json -o master_part_xt.json master_part_xt
# python xml2json.py -t xml2json -o master_part_xu.json master_part_xu
# python xml2json.py -t xml2json -o master_part_xv.json master_part_xv
# python xml2json.py -t xml2json -o master_part_xw.json master_part_xw
# python xml2json.py -t xml2json -o master_part_xx.json master_part_xx
# python xml2json.py -t xml2json -o master_part_xy.json master_part_xy
# python xml2json.py -t xml2json -o master_part_xz.json master_part_xz
# python xml2json.py -t xml2json -o master_part_ya.json master_part_ya
# python xml2json.py -t xml2json -o master_part_yb.json master_part_yb
# python xml2json.py -t xml2json -o master_part_yc.json master_part_yc
# python xml2json.py -t xml2json -o master_part_yd.json master_part_yd
# python xml2json.py -t xml2json -o master_part_ye.json master_part_ye
# python xml2json.py -t xml2json -o master_part_yf.json master_part_yf
# python xml2json.py -t xml2json -o master_part_yg.json master_part_yg
# python xml2json.py -t xml2json -o master_part_yh.json master_part_yh
# python xml2json.py -t xml2json -o master_part_yi.json master_part_yi
# python xml2json.py -t xml2json -o master_part_yj.json master_part_yj
# python xml2json.py -t xml2json -o master_part_yk.json master_part_yk
# python xml2json.py -t xml2json -o master_part_yl.json master_part_yl
# python xml2json.py -t xml2json -o master_part_ym.json master_part_ym
# python xml2json.py -t xml2json -o master_part_yn.json master_part_yn
# python xml2json.py -t xml2json -o master_part_yo.json master_part_yo
# python xml2json.py -t xml2json -o master_part_yp.json master_part_yp
# python xml2json.py -t xml2json -o master_part_yq.json master_part_yq
# python xml2json.py -t xml2json -o master_part_yr.json master_part_yr
# python xml2json.py -t xml2json -o master_part_ys.json master_part_ys
# python xml2json.py -t xml2json -o master_part_yt.json master_part_yt
# python xml2json.py -t xml2json -o master_part_yu.json master_part_yu
# python xml2json.py -t xml2json -o master_part_yv.json master_part_yv
# python xml2json.py -t xml2json -o master_part_yw.json master_part_yw
# python xml2json.py -t xml2json -o master_part_yx.json master_part_yx
# python xml2json.py -t xml2json -o master_part_yy.json master_part_yy
# python xml2json.py -t xml2json -o master_part_yz.json master_part_yz
# python xml2json.py -t xml2json -o master_part_za.json master_part_za
# python xml2json.py -t xml2json -o master_part_zb.json master_part_zb
# python xml2json.py -t xml2json -o master_part_zc.json master_part_zc
# python xml2json.py -t xml2json -o master_part_zd.json master_part_zd
# python xml2json.py -t xml2json -o master_part_ze.json master_part_ze
# python xml2json.py -t xml2json -o master_part_zf.json master_part_zf
# python xml2json.py -t xml2json -o master_part_zg.json master_part_zg
# python xml2json.py -t xml2json -o master_part_zh.json master_part_zh
# python xml2json.py -t xml2json -o master_part_zi.json master_part_zi
# python xml2json.py -t xml2json -o master_part_zj.json master_part_zj
# python xml2json.py -t xml2json -o master_part_zk.json master_part_zk
# python xml2json.py -t xml2json -o master_part_zl.json master_part_zl
# python xml2json.py -t xml2json -o master_part_zm.json master_part_zm
# python xml2json.py -t xml2json -o master_part_zn.json master_part_zn
# python xml2json.py -t xml2json -o master_part_zo.json master_part_zo
# python xml2json.py -t xml2json -o master_part_zp.json master_part_zp
# python xml2json.py -t xml2json -o master_part_zq.json master_part_zq
# python xml2json.py -t xml2json -o master_part_zr.json master_part_zr
# python xml2json.py -t xml2json -o master_part_zs.json master_part_zs
# python xml2json.py -t xml2json -o master_part_zt.json master_part_zt
# python xml2json.py -t xml2json -o master_part_zu.json master_part_zu
# python xml2json.py -t xml2json -o master_part_zv.json master_part_zv
# python xml2json.py -t xml2json -o master_part_zw.json master_part_zw
# python xml2json.py -t xml2json -o master_part_zx.json master_part_zx
# python xml2json.py -t xml2json -o master_part_zy.json master_part_zy
# python xml2json.py -t xml2json -o master_part_zz.json master_part_zz

